# A workflow to test waiting for SSH connections to the runner, when an error occurs.
name: Connection Test - On Error
on:
  pull_request:
    paths:
    - ci_connection
    - .github/workflows/wait-for-connection-on-error-test.yaml
    branches:
      - main
      - wait_connect_on_error
# Cancel any previous iterations if a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  wait-test:
    strategy:
      fail-fast: false
      matrix:
        runner: ["linux-x86-n2-16"]
        instances: ["1"]
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 60
    container:
      image: us-central1-docker.pkg.dev/tensorflow-sigs/tensorflow/ml-build@sha256:cec01011e627c0fd101c521a8af7c09ce4557ab6dcc9f8678aeb67a3182ed821 # ratchet:tensorflow/ml-build:latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # ratchet:actions/checkout@v4
      - name: Echo
        shell: bash  # required as the default `sh` doesn't have the ERR status
        run: |
          set -x
          trap 'PYTHONUNBUFFERED=1 python ci_connection/wait_on_error.py --shell-command "$BASH_COMMAND"' ERR
          echo "Real job here..."
          ls fake_directory_that_does_not_exist_most
